### ISSUE TITLE
Dynamically generated class properties are not accessible

### ISSUE THREAD

**Issue by afsafzal** [squaresLab/Houston#139]
The `uid` property of `Command` is dynamically set in `__init__` function of the MetaClass. But when accessed it returns a property object:
```
In [1]: from houston.ardu.common import ArmDisarm
In [2]: ArmDisarm.uid
Out[2]: <property at 0x7f1354389868>
```
But when `uid` is set with a string it works with no problem:
```
> GoTo.uid
'ardu:copter:goto'
```

The same thing applies to property `name` in `System` (even if it's set by a string):
```
In [6]: ArduCopter.name
Out[6]: <property at 0x7f13540e1d18>
```

**Comment by ChrisTimperley** [comment]
This is fixed?

**Comment by afsafzal** [comment]
No. I accidentally created two issues. #138 is the one.
