### ISSUE TITLE
Catch and log connection errors during trace collection

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/Houston#166]

**Comment by afsafzal** [comment]
@ChrisTimperley can you remind me what this is referring to?

**Comment by ChrisTimperley** [comment]
I don't think that we're explicitly catching and logging `ConnectionLostError` and `ConnectionFailedError` exceptions during trace collection in `build_traces.py`. https://github.com/squaresLab/Houston/pull/169/files takes care of this to some degree by catching all exceptions, but it would be nice to handle these exceptions a little differently (since they suggest that the SITL has crashed).
